[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D39E0EF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e61b0e16f221433fa5738aa51c9c6f04
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D39E0F020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e61b0e16f221433fa5738aa51c9c6f04
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D39E0F1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e61b0e16f221433fa5738aa51c9c6f04