{"name": "test_verify_login_with_invalid_username", "status": "passed", "start": 1721882934127, "stop": 1721882934773, "uuid": "42b7f9b0-0028-4681-badd-fabf8609650a", "historyId": "f5d1e6bc02260ccd5e4bd47a47c4a927", "testCaseId": "f5d1e6bc02260ccd5e4bd47a47c4a927", "fullName": "test.test_Login.TestLogin#test_verify_login_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-9A3ESFK"}, {"name": "thread", "value": "12184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_Login"}]}