[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219CA775130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15b228a26d8ac1a1fec6c3a07923dca7
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219CA774E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15b228a26d8ac1a1fec6c3a07923dca7
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219CA774E00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15b228a26d8ac1a1fec6c3a07923dca7